---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- block:
  - name: Install deluge
    apt:
      name: deluged
      state: present

  - name: Install deluge-console
    apt:
      name: deluge-console
      state: present

  - name: Install deluge-web
    apt:
      name: deluge-web
      state: present
  become: yes

- name: start deluge to init files
  command: deluged

- name: deluge-console config commands
  command: deluge-console config -s allow_remote True && deluge-console config allow_remote

- name: restart deluged (1/2)
  command: pkill deluged

- name: save old auth
  command: cp ~/.config/deluge/auth ~/.config/deluge/auth.old

- name: copy new auth
  template:
    src: auth-deluge.j2
    dest: ~/.config/deluge/auth

- name: config to run deluge-dameon at startup
  template:
    src: start-up-deluge.j2
    dest: /etc/init.d/deluge-daemon
  become: yes

- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false

- name: "Install YaRSS2 plugin"
  copy:
    src: /Users/charlesparent/Projects/rasp/ansible-pi/YaRSS2-1.4.3-py2.7.egg
    dest: ~/.config/deluge/plugins/
    owner: pi

- name: restart deluged (2/2)
  command: deluged && deluge-web

- name: Launch deluged deluge-web at start up
  blockinfile:
    path: /etc/rc.local
    insertbefore: exit 0
    block: |
      uuid=59D7-A6BA
      diskPresent='lsblk -f | grep -wq $uuid && echo yes || echo no'

      if [ "$diskpresent" = "yes" ]; then
        sudo -u pi deluged
        deluge-web&
      fi
  become: yes
