---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- stat: path={{'/media/NASDisk'}}
  register: NASDisk

- stat: path={{'/media/CHASINGDISK'}}
  register: CHASINGDISK

- block:
  - name: Creates directory NASDisk
    file:
      path: /media/NASDisk
      state: directory
      owner: pi
      group: pi
      mode: 0664
      recurse: yes
    when: NASDisk.stat.exists == False

  - name: Creates directory CHASINGDISK
    file:
      path: /media/CHASINGDISK
      state: directory
      owner: pi
      group: pi
      mode: 0664
      recurse: yes
    when: CHASINGDISK.stat.exists == False

  - name: Auto mount ChasingDisk drive at boot
    lineinfile:
      dest: /etc/fstab
      line: 'UUID=1518-3E99 /media/CHASINGDISK vfat defaults,nofail,uid=pi,gid=pi 0 0'

      insertafter: EOF
      create: True

  - name: Auto mount NASDisk drive at boot
    lineinfile:
      dest: /etc/fstab
      line: 'UUID=59D7-A6BA /media/NASDisk exfat defaults,auto,nofail,umask=000,users,rw,uid=pi,gid=pi 0 0'
      insertafter: EOF
      create: True
  become: yes
